### ISSUE TITLE
Incorrect Next Update is displayed in web interface

### ISSUE THREAD

**Issue by ties** [NLnetLabs/JDR-web#31]
The next update of a CRL appears to be displayed incorrectly in the web interface. This likely is caused by the data coming from the backend.

If I look up the RIPE NCC CRL for the off-line CA, https://jdr.nlnetlabs.nl/#/search/ripe-ncc-ta.crl
I see:
<img width="622" alt="Screenshot 2021-02-17 at 12 06 29" src="https://user-images.githubusercontent.com/199058/108195795-93ef0100-7118-11eb-9054-2e3ce4ac2f33.png">

If i look in the data [returned by the API](https://jdr.nlnetlabs.nl/api/v1/object/%2Frpki-repo%2Frsync%2Frpki.ripe.net%2Frepository%2Fripe-ncc-ta.crl), I do see the correct `Next Update` value.
```
$ curl https://jdr.nlnetlabs.nl/api/v1/object/%2Frpki-repo%2Frsync%2Frpki.ripe.net%2Frepository%2Fripe-ncc-ta.crl 2>/dev/null | jq '.data.object'
{
  "revoked_serials": [
    222,
    224,
    226,
    228,
    230,
    231
  ],
  "this_update": "2021-02-12T08:34:33.0",
  "next_update": "2021-05-12T08:34:33.0"
}
```

This is equal to what I see in the source file
```
$ rsync -a rsync://rpki.ripe.net/repository/ripe-ncc-ta.crl . && openssl crl -inform DER -in ripe-ncc-ta.crl -noout -text | head -n 8
The RIPE NCC Certification Repository is subject to Terms and Conditions
See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /CN=ripe-ncc-ta
        Last Update: Feb 12 08:34:33 2021 GMT
        Next Update: May 12 08:34:33 2021 GMT
        CRL extensions:
            X509v3 Authority Key Identifier:
```

**Comment by DRiKE** [comment]
Thank you very much for the elaborate description. I've found the culprit and fixed it, will be deployed shortly.
