### ISSUE TITLE
API

### ISSUE THREAD

**Issue by 0verloader** [NLnetLabs/JDR-web#32]
Does JDR provide an API so that we can easily fetch data?

**Comment by DRiKE** [comment]
There is an API, though it is quite tailored to the current web-interface and not well-described/documented for other uses. So depending on your use-case it might not be very convenient at this stage. Moreover, we have some changes lined up where the webservice part is split out of the main library which will cause some breaking changes. 

The current version allows you to search for resources, and request detailed info in a subsequent query. Searching for resources happens based on ASN, prefix or (part of) a filename, e.g.:
`curl https://jdr.nlnetlabs.nl/api/v1/asn/3333`
`curl https://jdr.nlnetlabs.nl/api/v1/prefix/185.49.140.0/22`
`curl https://jdr.nlnetlabs.nl/api/v1/filename/%203138352e34392e3134322e302f32332d3233203d3e203134363138.roa`

In those results you'll find an 'object filename' for every node in the tree, which can be used to fetch the details, e.g.:
`curl https://jdr.nlnetlabs.nl/api/v1/object/%2Frpki-repo%2Frrdp%2Frsync.krill.cloud%2Frepo%2Fnlnetlabs%2F1%2F3138352e34392e3134322e302f32332d3233203d3e203134363138.roa`

Please note that the system is not deployed to be heavily, programmatically queried in any way.

What is your use-case? Perhaps we can take it into consideration while refactoring the webservice part.
