### ISSUE TITLE
Repositories Tab on the webpage is broken

### ISSUE THREAD

**Issue by cli0** [NLnetLabs/JDR-web#33]
Hi,
I'd like to report that the Repositories tab on the webpage does not work anymore. I tested it both in Firefox and Chrome so it is not a browser issue.

This is what I see all the time:

![jdr](https://github.com/NLnetLabs/JDR-web/assets/25091717/701b3405-0df6-453a-a45e-243acc47144c)

**Comment by DRiKE** [comment]
Thanks for your report.
Indeed this is not a browser issue: there is something causing JDR to end up in a bogus state, causing this non-functional behavior. We still need to pinpoint what causes this exactly though.
As we are considering a significant overhaul for JDR entirely, I'll close this for now.
